apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
      - name: search-service
        image: adapirjol/search-service:latest
        env:
          - name: YOUTUBE_API_KEY
            value: AIzaSyA1XMpf0AEls3VkR8wA0ER7OxFEO64T5EA
        ports:
        - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: search-service
spec:
  selector:
    app: search-service
  ports:
    - port: 5003
      targetPort: 5003
